### ISSUE TITLE
Add instructions on how to package a service for inclusion in coolify

### ISSUE THREAD

**Issue by tiero** [coollabsio/documentation#7]
I have a bunch of services I want to propose for inclusion and want to help package them myself, I assume also others would use coolify as marketplace for their open-source alternative.

**Comment by compgeniuses** [comment]
i think due to the fact that Andras is working on a new implementation of the services, he may postpone working on this, however i am not sure when the new implementation might be coming

**Comment by andrasbacsai** [comment]
It is documented [here](https://github.com/coollabsio/coolify-community-templates).
